name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run tests
        run: mvn test